### ISSUE TITLE
Cleanup iCubInterface-related configuration files

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#145]
As emerged in https://github.com/robotology/icub-main/issues/632, in this repo there are a lot of configuration files for the iCubInterface executable, that have been deprecated by `robotinterface`/`yarprobotinterface` in ~2012 and removed from the icub-main repo in 2016 (see https://github.com/robotology/icub-main/commit/c6038729c9a3401a2d047a20c756867c35692944). 
We need to understand what to do with iCubInteface-related files still contained in this repo (see https://github.com/robotology/robots-configuration/search?utf8=%E2%9C%93&q=net_headtorso&type= for a short overview). I think it is perfectly safe to remove them.

**Comment by pattacini** [comment]
The search leads to files in `robots-icebox` and `iCubTemplates` (which we still retain).
I think we can close this issue now.
