### ISSUE TITLE
Add Gh action for CI

### ISSUE THREAD

**Issue by Nicogene** [robotology/robots-configuration#161]
We should add a gh for the continuous integration

**Comment by marcoaccame** [comment]
nice idea @Nicogene. 

would you like to deal w/ this issue? 

it may also be of interest of other iCubTech-ers willing to learn if you show them how you do it.

**Comment by Nicogene** [comment]
Added https://github.com/robotology/robots-configuration/commit/95718373cc87c18a2fb0c2976cdd5819b2ec2feb
