### ISSUE TITLE
Where to report robot configuration files issues

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#17]
I think there is a risk of overlap between the issue tracker of this repo (`robots-configuration`) and [`icub-support`](https://github.com/robotology/icub-support) that covers issue relative to a specific instance of a robot. 

Where should problems related to errors in configuration files be reported? Here or in icub-support? 
What do you prefer to have them @julijenv ?

**Comment by davidetome** [comment]
I think it's better to have them in robots-configuration.

**Comment by traversaro** [comment]
Perfect, thanks!
