### ISSUE TITLE
iCubOsaka01 missing iKinGazeCtrl conf file

### ISSUE THREAD

**Issue by pattacini** [robotology/robots-configuration#172]
> So, `YARP_ROBOT_NAME` is available, although `iKinGazeCtrl` gets configured based on its standard options, which are not robot specific. This may lead to incongruences.

I got it. `iCubOsaka01` doesn't contain any robot-specific conf file for `iKinGazeCtrl`.
I consider this a bug. We will fix this soon.

cc @marcoaccame

_Originally posted by @pattacini in https://github.com/robotology/QA/issues/388#issuecomment-595713749_

**Comment by pattacini** [comment]
@Fabrizio69 can you tell me the HW version of the `iCubOsaka01` head? 🤖

**Comment by Fabrizio69** [comment]
@pattacini the `iCubOsaka01` head is a 2.0 version (S/N: 028H)
