### ISSUE TITLE
iCubGenova02 not starting after #178

### ISSUE THREAD

**Issue by lrapetti** [robotology/robots-configuration#186]
After #178 was merged, the startup is failing. It is correctly started by moving back to previous commit https://github.com/robotology/robots-configuration/commit/1a05e7825afcab6ade8a9477b56f584c95a18ccf.

I think the problem is due to the fact that the Firmware of the robot FTs is not updated.
CC @marcoaccame 

Here is the output:
[log.txt](https://github.com/robotology/robots-configuration/files/4786993/log.txt)

The following error seems to be repeated for all the boards:
```
...
[WARNING]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 520m 402u: CAN discovery has detected a eobrd_strain2 board in CAN2 addr 13 with can protocol ver 2.0 and application ver 2.0.4 Search time was 2 ms
[ERROR] embObjStrain::open() has an error in call of ethResources::serviceVerifyActivate() for BOARD left_leg-eb6-j0_3 IP 10.0.1.6
[INFO] The embObjStrain device using BOARD left_leg-eb6-j0_3  w/ IP 10.0.1.6 has the following service config:
[INFO] - acquisitionrate = 10
[INFO] - useCalibration = true
[INFO] - STRAIN of type strain2 named id_l_upper_leg_strain @ CAN2:13 with required protocol version = (2, 0) and required firmware version = (2, 0, 7)
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 520m 547u: CAN discovery has detected 1 invalid eobrd_strain2 boards in CAN2:
[ERROR] 1 of 1: wrong eobrd_strain2 BOARD 10.0.1.6:CAN2:13 because it has:  WRONG APPLICATION VERSION 
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 81s 520m 685u: (code 0x05000009, par16 0x010d par64 0x0000000202000200) -> CFG: EOtheSTRAIN cannot be configured. can discovery fails. can address in p16, prot and vers in p64 lower 32 bits. Byte 5 of p64: 0x01 is strain, 0x02 is strain2 + .
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 81s 520m 814u: (code 0x05000009, par16 0x010d par64 0x0000000202000200) -> CFG: EOtheSTRAIN cannot be configured. can discovery fails. can address in p16, prot and vers in p64 lower 32 bits. Byte 5 of p64: 0x01 is strain, 0x02 is strain2 + .
[WARNING]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 520m 967u: CAN discovery has detected a eobrd_strain2 board in CAN2 addr 13 with can protocol ver 2.0 and application ver 2.0.4 Search time was 2 ms
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 521m 115u: CAN discovery has detected 1 invalid eobrd_strain2 boards in CAN2:
[ERROR] 1 of 1: wrong eobrd_strain2 BOARD 10.0.1.6:CAN2:13 because it has:  WRONG APPLICATION VERSION 
[WARNING]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 81s 521m 555u: (code 0x0000000b, par16 0x03c7 par64 0x0062003300980020) -> SYS: the RX phase of the control loop has last more than wanted. In par16: RX execution time [usec]. In par64: latest previous execution times of TX, RX, DO, TX [usec] + .
[WARNING]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 81s 522m 305u: (code 0x0000000b, par16 0x01d9 par64 0x002003c702e10225) -> SYS: the RX phase of the control loop has last more than wanted. In par16: RX execution time [usec]. In par64: latest previous execution times of TX, RX, DO, TX [usec] + .
yarpdev: ***ERROR*** driver <embObjStrain> was found but could not open
...
```

**Comment by julijenv** [comment]
Ciao @lrapetti ,
coudl you please remove the entire log file you add to the issue and put everything in one file . txt, it is way more readable that way.
thx in advance

**Comment by marcoaccame** [comment]
yes, the firmware of the robot is not updated. 
in particular the log tells that the required fw version of strain2 board is 2.0.7 and there is still 2.0.4.

```
[INFO] - STRAIN of type strain2 named id_l_upper_leg_strain @ CAN2:13 
 with required protocol version = (2, 0) and required firmware version = (2, 0, 7)
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 520m 547u: CAN discovery 
has detected 1 invalid eobrd_strain2 boards in CAN2:
[WARNING]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3) @ 81s 520m 967u: CAN discovery has 
detected a eobrd_strain2 board in CAN2 addr 13 with 
can protocol ver 2.0 and application ver 2.0.4 Search time was 2 ms
[ERROR] 1 of 1: wrong eobrd_strain2 BOARD 10.0.1.6:CAN2:13 because it has:  
WRONG APPLICATION VERSION 
```

the required fw version for every board in the robot are in file: https://github.com/robotology/icub-firmware-build/blob/master/info/firmware.info.xml), and instructions on how to update are in https://github.com/robotology/icub-firmware-build/tree/master/docs

**Comment by lrapetti** [comment]
> yes, the firmware of the robot is not updated.

Thanks @marcoaccame. 

Some of the main `iCubGenova02` users might be using old configuration files for whom the current firmware is working. I don't want to brake their applications.
I think @marco-monforte @GiuliaDAngelo (with the other `iCubGenova02` users) can decide wether/when to proceed with the update of the robot firmware.

**Comment by marco-monforte** [comment]
Hi everyone, I'll check that we don't have any issue in updating the firmware and I'll do it as soon as possible.

**Comment by marco-monforte** [comment]
Hey guys, the firmware has been updated and now the strain2 has the 2.0.7 version.

Thanks for the help @marcoaccame .

@lrapetti when you want, we can try what you were doing and close the issue hopefully.

**Comment by lrapetti** [comment]
Thanks @marco-monforte @marcoaccame, we tried to run the robot with the configuration file in master ([`icub_wbd.xml`](https://github.com/robotology/robots-configuration/blob/master/iCubGenova02/icub_wbd.xml)) and it started correctly.

We can close the issue.
