### ISSUE TITLE
On several robot, the eyes_version and eyes_vergence AxisName are inverted

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#19]
See (for example, there are others):
* https://github.com/robotology/robots-configuration/blob/5f349195c9d158e73cedcf805b032afb6a5e27d3/iCubDarmstadt01/hardware/mechanicals/head-cfw2_can0-mec.xml#L9
* https://github.com/robotology/robots-configuration/blob/5f349195c9d158e73cedcf805b032afb6a5e27d3/iCubGenova01/hardware/motorControl/icub_head_test.xml#L36

The official ordering (from http://wiki.icub.org/wiki/ICub_joints#Head_2.0) should be "eyes_version" "eyes_vergence".

**Comment by davidetome** [comment]
fixed , found 3 robots
