### ISSUE TITLE
Some of the gear ratios of the iCubGenova09 appear to be wrong

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/robots-configuration#216]
This issue was actually discovered by @pattacini @salvi-mattia. For example, the gear ratio on the ankle rolls is set to 160, but it is most probably 100

https://github.com/robotology/robots-configuration/blob/696b86c77e4e5bd9c4c0880010551e7705804f04/iCubGenova09/hardware/mechanicals/right_leg-eb12-j4_5-mec.xml#L14

Right now, this does not affect the position control loop, but it may be an issue for other types of controllers.

cc @traversaro @lrapetti

**Comment by pattacini** [comment]
That's correct, thanks @S-Dafarra for spotting 👍🏻
