### ISSUE TITLE
Head calibration delta parameter seems to have no effect 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/robots-configuration#35]
We were trying to calibrate the neck joints  on iCubNancy01. In the configuration file for the head ([here](https://github.com/robotology/robots-configuration/blob/master/iCubNancy01/calibrators/head-calib.xml)) we tried to modify the parameter `calibrationDelta`, but it seems that this parameters has no effect in the calibration procedure, and the joints always have the same error (according to the IMU measurements)

**Comment by traversaro** [comment]
Subset of https://github.com/robotology/icub-main/issues/388 .

**Comment by pattacini** [comment]
Stale PR, closing.
Feel free to open it again if needed.
