### ISSUE TITLE
Robot with XSens MT IMU in waist still spawn the IMU YARP Hardware Device via inertial instead of separating hardware and Network Wrapper Servers

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#355]
Before https://github.com/robotology/robots-configuration/pull/116 all the head IMUs were not spawned on their own, but they were spawned by launching an inertial YARP device and specifing the YARP Hardware device name via the `subdevice` parameter. This was fixed in https://github.com/robotology/robots-configuration/pull/116, in particular with the commits:
* https://github.com/robotology/robots-configuration/pull/116/commits/abb5cad9078490e3f3d0131c335f68f62cbd2c4c
* https://github.com/robotology/robots-configuration/pull/116/commits/b73b48ec8aa11db7c3365618a0cb3693ac8c4bed

This change was never propagate to the waist Xsens IMU that are accessed via the  [`xsensmt`](https://github.com/robotology/yarp-device-xsensmt) YARP hardware device. So, this device is still not expose via MAS (Multiple Anaog Sensor) interfaces.

**Comment by pattacini** [comment]
Thanks for reporting @traversaro 👍🏻 
We could address this during our next sprint PI11-sprint03 in two weeks.

**Comment by pattacini** [comment]
Fixed via #373 in `devel`.
