### ISSUE TITLE
Updated Black iCub configuration file after fine calibration

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/robots-configuration#38]
This is just a question about the configuration files in `robots-configuration/iCubGenova01/hardware/motorControl` of `iCubGenova01`.

Recently @giuliavezzani and I have fine calibrated the Black iCub and were wondering whether we should update such files here as well or not.
The robot head, torso and right arm were quite distant from the `Zeros`values.

**Comment by pattacini** [comment]
I would go for an update of the pristine values here in this repo as well 👍

**Comment by claudiofantacci** [comment]
Cool! No problem for us!

I'll then change the status of this issue to keep track of it and do a PR asap.

**Comment by claudiofantacci** [comment]
cc @giuliavezzani
