### ISSUE TITLE
Migration of all icub xml files to the new yri syntax

### ISSUE THREAD

**Issue by randaz81** [robotology/robots-configuration#417]
All robots configuration files should be migrated to the new syntax shown in https://github.com/robotology/robots-configuration/blob/master/R1SN003/CER.xml, so that a single main XML file can be used on all versions (with/without ros, with/without a specific part etc.)

**Comment by pattacini** [comment]
Closing this in favor of #641.

ergoCub is our new flagship so I think it suffices to narrow the effort and address the updating of those conf files.
