### ISSUE TITLE
Bad configuration files for the iCubNancy01 robot

### ISSUE THREAD

**Issue by misaki43** [robotology/robots-configuration#5]
Hello @pattacini and others,

I've just added the robot configuration files, but when I launch the robot, I can see there're some mistakes.

When I compare those files with other robots' configurations, I can see that sometimes the robot name is not defined, and other times, certain parameters are not the same (e.g., the `canDeviceNum` in hardware/skin/torso[...] or `kinematicTypeConnect` in the cartesian folder).

Can you correct all our robot-configuration files please?

[**Here is the log**](https://github.com/robotology/robots-configuration/files/511547/log.txt).

Thanks!

cc @serena-ivaldi @olivierrochel-inria

**Comment by pattacini** [comment]
@davidetome could you please deal with this request?

@misaki43 depending on the workload of @davidetome the fix might take some time. If you've already identified a bunch of errors you could think of pointing them out by opening a PR with the corresponding fixes. This will speed up the operations.

**Comment by davidetome** [comment]
I've just modified a couple of files removing warnings messages about syntax errors and committed them.
It should be tested on the robot.
p.s. CanDeviceNum in hardware/skin/torso[..] is correctly settled to 9 (the CAN port number on the cfw2 board)

**Comment by olivierrochel-inria** [comment]
thanks @davidetome; 
There's still a suspicious robot="iCubGenova04" in iCubNancy01/hardware/skin/torso-cfw2_can9-skin.xml, and possibly in iCub_Calibration_iCubVillersLesNancy01.xls but I can't open it. Can you check ?

**Comment by davidetome** [comment]
Hi @olivierrochel-inria ,

 I removed the incorrect entry and restored/renamed the xls file that was corrupted.
Please check and let us know.

**Comment by pattacini** [comment]
@misaki43 any feedback?

**Comment by misaki43** [comment]
Hello @davidetome @pattacini,
sorry for this lack of feedback, now all files seems good, thanks a lot!
