### ISSUE TITLE
ergoCubSN000: expose BMS on YARP network via `battery_nws_yarp`

### ISSUE THREAD

**Issue by Nicogene** [robotology/robots-configuration#506]
### Task description

We need to add the xml file for running `battery_nws_yarp` on `ergoCubSN000`.

### Definition of done

The xml files have been added and tested.

**Comment by martinaxgloria** [comment]
I open a PR in which I added the .xml files:

- https://github.com/robotology/robots-configuration/pull/514

It is still in draft since those files have to be tested on the robot. I booked ergoCub for tomorrow morning to do some other tests, but if I have time, I will do these too.
