### ISSUE TITLE
[ergoCubSN000] Gear ratio values of right and left shoulder roll joints do not match

### ISSUE THREAD

**Issue by isorrentino** [robotology/robots-configuration#545]
Hi all, while checking the parameters needed to control the motors in torque, I noticed that the gear ratio values of the right and left shoulder roll joints do not match. Do they have a different harmonic drive or is this an error? (See the parameter `Gearbox_M2J`).

- right
  https://github.com/robotology/robots-configuration/blob/c7c965a9aa1b8295ace3a32c2fb69c18c18794db/ergoCubSN000/hardware/mechanicals/right_arm-eb1-j0_1-mec.xml#L5-L19

- left
  https://github.com/robotology/robots-configuration/blob/c7c965a9aa1b8295ace3a32c2fb69c18c18794db/ergoCubSN000/hardware/mechanicals/left_arm-eb2-j0_1-mec.xml#L5-L19

cc @lrapetti @ale-git

**Comment by pattacini** [comment]
Thanks for reporting.

It's most likely an error, but I'm checking that out w/ @Mick3Lozzo.
Once done, I'll apply a patch.

**Comment by Mick3Lozzo** [comment]
![image](https://github.com/robotology/robots-configuration/assets/15085666/04e00ea7-db26-4751-a77d-47d2c6ff561c)

gear ratio = 100 @isorrentino 

cc @pattacini
