### ISSUE TITLE
Update maintained robots to the use of `multipleanalogsensorsserver` for `embObjMAIS` device

### ISSUE THREAD

**Issue by pattacini** [robotology/robots-configuration#563]
This is a follow-up of https://github.com/robotology/icub-main/issues/851 and aims to update our maintained robots to the use of non-deprecated YARP I/F.

cc @Nicogene @traversaro

**Comment by pattacini** [comment]
cc @randaz81

**Comment by davidetome** [comment]
Done in : 

- https://github.com/robotology/robots-configuration/pull/568

**Comment by pattacini** [comment]
Hi @davidetome 
The PR is in draft. Is it because you aim to perform some tests beforehand?
