### ISSUE TITLE
Enable tags not working for ros2

### ISSUE THREAD

**Issue by SimoneMic** [robotology/robots-configuration#663]
Hello,
I have tried the command for launching the YRI with ros2 enabled, as listed in this issue #641

However the format is not recognised:
```
yarprobotinterface --config ergocub.xml --enable_tags (enable_ros2) 
-bash: syntax error near unexpected token `('
```
I have also tried removing the brackets, the robot starts, but Ros is not enabled.
Also by removing the --config part. Same result.

**Comment by traversaro** [comment]
Can you try: 

~~~
yarprobotinterface --config ergocub.xml --enable_tags "(enable_ros2)"
~~~

Not sure why I did not experienced this problem, perhaps I tested on Windows.

**Comment by pattacini** [comment]
Any feedback @SimoneMic?

**Comment by SimoneMic** [comment]
I haven't used the robot today, when I'll have my slot I will test it

**Comment by pattacini** [comment]
Thanks!

**Comment by GiulioRomualdi** [comment]
```
yarprobotinterface --config ergocub.xml --disable_tags \(disable_right_arm\) 
```
works

**Comment by pattacini** [comment]
Uhm, the format with the escape char `\` doesn't seem very clear in the first place, unless it's reported in the documentation. If not, it should be pointed out in YARP, somehow cc @randaz81. 

Out of curiosity, does it mean that "(disable_right_arm)" doesn't work?

**Comment by SimoneMic** [comment]
With the "()" it works

**Comment by randaz81** [comment]
I never heard about the use of \, I think it works by chance (undocumented and to be avoided.)
Instead if i remeber correctly you should always use " to encapsulate a  ( ) block, independently if it contains multiple elements or just one, like in your case.

**Comment by pattacini** [comment]
Yeah, indeed, the standard ought to be `"(...)"`.
I remember now that I used it in the past for the `find-superquadric` module:
- https://github.com/robotology/find-superquadric?tab=readme-ov-file#example

I think we can close it.
Feel free to open it up again if you deem it necessary.

**Comment by traversaro** [comment]
> The documentation should be changed, I think

Which documentation?
