### ISSUE TITLE
id_x_hand_mais  used as sensor name in both left and right MAIS

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#679]
It seems that `id_x_hand_mais` is used as a ID (and hence a sensor name returned by [`getEncoderArrayName`](https://www.yarp.it/latest/classyarp_1_1dev_1_1IEncoderArrays.html#af223aea775badaf4053f19d711061ab6 method) for both left and right mais. This is problematic as it creates problems if one inserted both left and right mais in the same `MultipleAnalogSensorRemapper`. 

See for example:
* https://github.com/robotology/robots-configuration/blob/3e8fba8477fcf6ea9bba07add2956ada126d2684/iCubPrague01/hardware/MAIS/right_arm-eb29-j12_15-mais.xml#L33
* https://github.com/robotology/robots-configuration/blob/3e8fba8477fcf6ea9bba07add2956ada126d2684/iCubPrague01/hardware/MAIS/left_arm-eb26-j12_15-mais.xml#L33

To fix the issue, taking as an example FT sensors (see https://github.com/robotology/robots-configuration/blob/3e8fba8477fcf6ea9bba07add2956ada126d2684/iCubGenova10/hardware/FT/left_arm-eb1-j0_3-strain.xml#L33) we could change the mais ID to `l_hand_mais` and `r_hand_mais`.

**Comment by pattacini** [comment]
Good point.
I'll deal with that.
