### ISSUE TITLE
ETH Daisy Chain connection order in config

### ISSUE THREAD

**Issue by paraschos** [robotology/robots-configuration#7]
Refering to robotology/QA/issues/134 , @marcoaccame suggested 

> The chain of ETH boards can change from robot to robot. The correct action would be to add the HW schematics in a file inside robots-configuration repository.

which is something I totally agree it should be done.  I can do it for iCubDarmstadt01, however 
you might prefer a specific format/template.

**Comment by maggia80** [comment]
I commit the image of the robot configuration in this issue, but i will put it also in the repo. I hope it helps. iCubDarmastadt01 is a E3.1 robot 

![architectures_icub2 5_e3 1](https://cloud.githubusercontent.com/assets/6987330/25223910/1c64ff0e-25bd-11e7-98a7-46650cdd01bf.png)
![icub2 5-e3 2](https://cloud.githubusercontent.com/assets/6987330/25223911/1c66c82a-25bd-11e7-9efc-3c9d95976148.png)
